trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePhpVersion@0
    inputs:
      versionSpec: '7.x'
      addToPath: true

  - script: |
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      php -r "unlink('composer-setup.php');"
    displayName: 'Install Composer'

  - script: composer install --no-interaction --prefer-dist
    displayName: 'Install Dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<Azure Service Connection>'
      appName: '<App Service Name>'
      package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'